"""empty message

Revision ID: 99fdf4725c99
Revises: 7fce8210d3ca
Create Date: 2024-05-18 20:25:59.100103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fdf4725c99'
down_revision = '7fce8210d3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
